# Generated by Django 5.2.7 on 2025-11-18 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("firstapp", "0003_preset_created_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="preset",
            old_name="settings",
            new_name="data",
        ),
    ]
