# Generated by Django 5.2.7 on 2025-11-18 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("firstapp", "0004_rename_settings_preset_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="preset",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="presets/"),
        ),
    ]
